# DEFAULT

meta_product_name: "Moving on"
meta_title: "Moving on - Home clearance in the event of death"
meta_description: "An intuitive step-by-step assistant that provides relief in the event of death by resolving house clearance, all in one place."
meta_image: "https://picsum.photos/1200/630?image=1025"

